Generate the correct SERVER_PROTOCOL_VERSION.
Closes in development: #836911
Closes: #836566

SERVER_PROTOCOL_VERSION is used to check if the running server's
and the client's version match. It is set in
include/wine/server_protocol.h (490 in 1.8.4), and increased by
1 by make_requests. But we clean server_protocol.h because it is
generated, so SERVER_PROTOCOL_VERSION in Debian is always 1.

To fix this retrieve SERVER_PROTOCOL_VERSION on upstream import
before server_protocol.h is cleaned, and store it (decreased by
1) in request.patch. make_request will then regenerate
server_protocol.h with the correct SERVER_PROTOCOL_VERSION.

# Conflicts:
#	debian/changelog
#	debian/patches/generate/request.patch

Note cherrypick: Change initial version in requests.patch to 490
and adapt bug numbers.

diff --git a/debian/scripts/import b/debian/scripts/import
--- a/debian/scripts/import
+++ b/debian/scripts/import
@@ -49,3 +49,11 @@ dch -v "$version-1" "New upstream release $version, released $release_date."
 sed -n 's/^  - \(.*\)/- \1/p' ANNOUNCE | while read line; do
   dch $line
 done
+
+# set upstream's SERVER_PROTOCOL_VERSION in request.patch
+# this is usually stored in include/wine/server_protocol.h, but we clean that file because it is generated
+proto_version=$(expr $(grep "#define SERVER_PROTOCOL_VERSION" include/wine/server_protocol.h | cut -d\  -f 3) - 1)
+[ "$proto_version" -lt 32767 ] || {
+    echo "error: proto_version $proto_version is not valid."
+    exit 1;}
+sed -i "s|\(+    my \$protocol = \)[[:digit:]]*;|\1${proto_version};|" debian/patches/generate/request.patch
